<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "crt_std_func"
 *
 * Auto generated by Extension Builder 2014-09-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cretection Standard Functions',
	'description' => '',
	'category' => 'misc',
	'author' => 'Jonathan Starck, Jonathan Starck',
	'author_email' => 'info@cretection.eu, info@cretection.eu',
	'state' => 'beta',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => true,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'ws_less' => '1.3',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);